# fly.toml app configuration file generated for de-yi-clone-ora on 2026-05-17T19:34:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'de-yi-clone-ora'
primary_region = 'nrt'

[build]

[deploy]
  strategy = 'immediate'

[env]
  ORA_DAILY_FORTUNE_HOUR = '9'
  ORA_DB_PATH = '/data/ora.db'
  ORA_TIMEZONE = 'Asia/Seoul'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
